/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Login;


import Controller.DBConnection;
import UI.NhanVien.MainJFramesNV;
import UI.QuanLy.MainJFrames;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author THUAN NGUYEN
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        lblHide.setVisible(false);
        txtUsername.requestFocus();
    }

    public boolean validateForm() {
        if (txtUsername.getText().isEmpty()) {
            txtUsername.setBackground(Color.YELLOW);
            JOptionPane.showMessageDialog(this, "Tài khoản không được để trống!");
            txtUsername.requestFocus();
            return false;
        } else {
            Pattern pMaNV = Pattern.compile("PS[0-9]{5}");
            Matcher mMaNV = pMaNV.matcher(txtUsername.getText());
            if (!mMaNV.matches()) {
                JOptionPane.showMessageDialog(this, "Mã nhân viên nhập sai định dạng");
                txtUsername.requestFocus();
                txtUsername.setBackground(Color.pink);
                return false;
            } else {
                txtUsername.setBackground(Color.WHITE);
            }
        }

        if (txtPassword.getText().isEmpty()) {
            txtPassword.setBackground(Color.YELLOW);
            JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống!");
            txtPassword.requestFocus();
            return false;
        } else {
            txtPassword.setBackground(Color.WHITE);
        }
        if (!rdoAdmin.isSelected() && !rdoUser.isSelected()) {
            JOptionPane.showMessageDialog(this, "Chưa chọn vai trò đăng nhập!");
            return false;
        }
        return true;
    }

    void Login() {
        if (validateForm()) {
            PreparedStatement ps = null;
            Connection con = null;
            try {
                con = DBConnection.getConnection();
                String sql = "Select * from AccLogin,nhanvien where manv=userid and UserID=? and Pass=?";
                ps = con.prepareStatement(sql);
                ps.setString(1, txtUsername.getText());
                ps.setString(2, txtPassword.getText());
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    String s1 = rs.getString("RoleAcc");
                    String tennv=rs.getString("tennv");
                    if (txtUsername.getText().equals(rs.getString(1)) && txtPassword.getText().equals(rs.getString(2))) {
                        if (rdoAdmin.isSelected() && s1.equals("Quản lý")) {
                            JOptionPane.showMessageDialog(null, "Đăng nhập thành công");
                            MainJFrames main = new MainJFrames();//
                            main.getten(tennv);
                            main.setVisible(true);
                            this.dispose();
                        } else if (rdoUser.isSelected() && (s1.equals("Nhân Viên") || s1.equalsIgnoreCase("Quản lý"))) {
                            JOptionPane.showMessageDialog(null, "Đăng nhập thành công!");
                            MainJFramesNV main = new MainJFramesNV();//
                            
                            main.username(tennv);
                            main.setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "Đăng nhập thất bại!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Đăng nhập thất bại!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Đăng nhập thất bại!");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrRole = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jpnRoot = new javax.swing.JPanel();
        jpnLogin = new javax.swing.JPanel();
        lbForgotPassWord = new javax.swing.JLabel();
        lblDangNhap = new javax.swing.JLabel();
        lblLine = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblShow = new javax.swing.JLabel();
        lblHide = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblIconUser = new javax.swing.JLabel();
        lblIconPass = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        rdoAdmin = new javax.swing.JRadioButton();
        rdoUser = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(450, 650));
        setMinimumSize(new java.awt.Dimension(450, 650));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(450, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(450, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnRoot.setMaximumSize(new java.awt.Dimension(450, 650));
        jpnRoot.setMinimumSize(new java.awt.Dimension(450, 650));
        jpnRoot.setPreferredSize(new java.awt.Dimension(450, 650));
        jpnRoot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnLogin.setBackground(new java.awt.Color(255, 255, 255));
        jpnLogin.setPreferredSize(new java.awt.Dimension(320, 500));
        jpnLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbForgotPassWord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbForgotPassWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbForgotPassWord.setText("Quên mật khẩu?");
        lbForgotPassWord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbForgotPassWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbForgotPassWordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbForgotPassWordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbForgotPassWordMouseExited(evt);
            }
        });
        jpnLogin.add(lbForgotPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 130, -1));

        lblDangNhap.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblDangNhap.setForeground(new java.awt.Color(0, 51, 153));
        lblDangNhap.setText("ĐĂNG NHẬP");
        jpnLogin.add(lblDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 40));

        lblLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login/line.jpg"))); // NOI18N
        jpnLogin.add(lblLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 70, 340, 10));

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnLogin.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 210, 35));

        lblShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login/hidden.png"))); // NOI18N
        lblShow.setPreferredSize(new java.awt.Dimension(38, 35));
        lblShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblShowMousePressed(evt);
            }
        });
        jpnLogin.add(lblShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 30, -1));

        lblHide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login/eye.png"))); // NOI18N
        lblHide.setPreferredSize(new java.awt.Dimension(38, 35));
        lblHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHideMousePressed(evt);
            }
        });
        jpnLogin.add(lblHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 30, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnLogin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 210, 35));

        lblIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login/user.png"))); // NOI18N
        jpnLogin.add(lblIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 20, 30));

        lblIconPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login/door-key.png"))); // NOI18N
        jpnLogin.add(lblIconPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 20, 30));

        btnLogin.setBackground(new java.awt.Color(0, 102, 153));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login/login.png"))); // NOI18N
        btnLogin.setText("Xác nhận");
        btnLogin.setToolTipText("");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jpnLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 210, 40));

        btnCancel.setBackground(new java.awt.Color(255, 102, 102));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login/power-off.png"))); // NOI18N
        btnCancel.setText("Thoát");
        btnCancel.setToolTipText("");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jpnLogin.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, 40));

        rdoAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btngrRole.add(rdoAdmin);
        rdoAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoAdmin.setText("Quản lý");
        jpnLogin.add(rdoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        rdoUser.setBackground(new java.awt.Color(255, 255, 255));
        btngrRole.add(rdoUser);
        rdoUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoUser.setText("Bán hàng");
        jpnLogin.add(rdoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        jpnRoot.add(jpnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 470));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login/bn.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(450, 650));
        jLabel2.setMinimumSize(new java.awt.Dimension(450, 650));
        jLabel2.setPreferredSize(new java.awt.Dimension(450, 650));
        jpnRoot.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 650));

        getContentPane().add(jpnRoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 650));

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int ret = JOptionPane.showConfirmDialog(this, "Bạn muốn thoát?", "Xác nhận",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (ret == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            txtUsername.requestFocus();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void lblShowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowMousePressed
        lblHide.setVisible(true);
        lblShow.setVisible(false);
        txtPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_lblShowMousePressed

    private void lblHideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHideMousePressed
        lblHide.setVisible(false);
        lblShow.setVisible(true);
        txtPassword.setEchoChar('*');
    }//GEN-LAST:event_lblHideMousePressed

    private void lbForgotPassWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbForgotPassWordMouseClicked
        FormForgotPass fg = new FormForgotPass(this, true);
        fg.setVisible(true);
    }//GEN-LAST:event_lbForgotPassWordMouseClicked

    private void lbForgotPassWordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbForgotPassWordMouseEntered
        lbForgotPassWord.setForeground(Color.BLUE);
    }//GEN-LAST:event_lbForgotPassWordMouseEntered

    private void lbForgotPassWordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbForgotPassWordMouseExited
        lbForgotPassWord.setForeground(Color.black);
    }//GEN-LAST:event_lbForgotPassWordMouseExited

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        Login();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Login().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.ButtonGroup btngrRole;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpnLogin;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JLabel lbForgotPassWord;
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JLabel lblHide;
    private javax.swing.JLabel lblIconPass;
    private javax.swing.JLabel lblIconUser;
    private javax.swing.JLabel lblLine;
    private javax.swing.JLabel lblShow;
    private javax.swing.JRadioButton rdoAdmin;
    private javax.swing.JRadioButton rdoUser;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
